In [17]:
import sys

print("Python used by notebook:")
print(sys.executable)

Python used by notebook:
c:\Users\ansh\anaconda3\python.exe

In [18]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "faiss-cpu"
])

0

In [19]:
import faiss

print("FAISS imported successfully!")
print("FAISS version:", faiss.__version__)

FAISS imported successfully!
FAISS version: 1.15.0

In [20]:
import sys
import subprocess

print("Python:", sys.executable)

result = subprocess.run(
    [sys.executable, "-m", "pip", "show", "faiss-cpu"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Python: c:\Users\ansh\anaconda3\python.exe
Name: faiss-cpu
Version: 1.15.0
Summary: A library for efficient similarity search and clustering of dense vectors.
Home-page: https://github.com/facebookresearch/faiss
Author: Meta AI Research
Author-email:
License-Expression: MIT
Location: c:\Users\ansh\anaconda3\Lib\site-packages
Requires: numpy, packaging
Required-by:

In [21]:
import sys
import subprocess

print("Python:", sys.executable)

result = subprocess.run(
    [sys.executable, "-m", "pip", "show", "faiss-cpu"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Python: c:\Users\ansh\anaconda3\python.exe
Name: faiss-cpu
Version: 1.15.0
Summary: A library for efficient similarity search and clustering of dense vectors.
Home-page: https://github.com/facebookresearch/faiss
Author: Meta AI Research
Author-email:
License-Expression: MIT
Location: c:\Users\ansh\anaconda3\Lib\site-packages
Requires: numpy, packaging
Required-by:

In [22]:
corpus = [
    # AI / Machine Learning
    "Machine learning systems learn patterns from historical data to make predictions.",
    "Neural networks are computing models inspired by the structure of biological brains.",
    "Natural language processing enables computers to understand and generate human language.",
    "Computer vision allows machines to interpret information from images and videos.",
    "Large language models can generate text, answer questions, and summarize documents.",
    "Retrieval augmented generation combines language models with external knowledge sources.",
    "Embeddings represent text as numerical vectors that capture semantic meaning.",
    "Fine tuning adapts a pretrained model to perform better on a specialized task.",
    "Prompt engineering involves designing instructions that guide language model behavior.",
    "Tokenization breaks text into smaller units that language models can process.",

    # Cloud
    "Cloud computing provides computing resources over the internet on demand.",
    "Virtual machines allow multiple isolated computing environments to run on shared hardware.",
    "Containers package applications with their dependencies so they can run consistently.",
    "Kubernetes orchestrates containers across clusters of machines.",
    "Serverless computing allows developers to run code without managing servers directly.",
    "Auto scaling increases or decreases computing resources based on workload demand.",
    "Object storage is designed for storing large amounts of unstructured data.",
    "Cloud load balancers distribute incoming traffic across multiple application instances.",
    "Infrastructure as code manages infrastructure through version-controlled configuration files.",
    "Cloud monitoring tracks application health, performance, and resource utilization.",

    # Databases
    "Relational databases organize information into tables containing rows and columns.",
    "SQL is used to query and manipulate data stored in relational databases.",
    "Database indexes improve query performance by making data retrieval more efficient.",
    "Transactions ensure that groups of database operations are completed reliably.",
    "Database normalization reduces unnecessary duplication of information.",
    "NoSQL databases are useful for flexible schemas and certain large-scale workloads.",
    "Data warehouses are optimized for analytical queries over large historical datasets.",
    "Data lakes store large volumes of raw structured and unstructured information.",
    "ETL pipelines extract data, transform it, and load it into a target system.",
    "Data quality processes help ensure that analytical datasets are accurate and consistent.",

    # Software Engineering
    "Git tracks changes to source code and enables collaboration between developers.",
    "Continuous integration automatically builds and tests software changes.",
    "Continuous deployment automates the release of tested software into production.",
    "Unit tests verify individual functions or components in isolation.",
    "Integration tests verify that multiple software components work correctly together.",
    "Code reviews help teams identify defects and improve software quality.",
    "Application programming interfaces allow different software systems to communicate.",
    "Microservices divide applications into smaller independently deployable services.",
    "Caching stores frequently accessed information so future requests can be served faster.",
    "Message queues allow applications to communicate asynchronously.",

    # Cybersecurity
    "Cybersecurity protects systems, networks, and information from unauthorized access.",
    "Authentication verifies the identity of a user or service.",
    "Authorization determines which resources an authenticated user is allowed to access.",
    "Encryption protects information by transforming readable data into protected ciphertext.",
    "Multi factor authentication adds additional verification beyond a password.",
    "Phishing attacks attempt to trick users into revealing sensitive information.",
    "Firewalls control network traffic based on predefined security rules.",
    "Security monitoring helps organizations detect suspicious activity and potential attacks.",
    "Vulnerability scanning identifies weaknesses in applications and infrastructure.",
    "Least privilege gives users and services only the permissions they actually need.",

    # Data Engineering
    "Data engineering focuses on building systems that collect, transform, and deliver data.",
    "Apache Spark enables distributed processing of large datasets across clusters.",
    "Batch processing handles data in groups at scheduled or triggered intervals.",
    "Stream processing analyzes events continuously as they are generated.",
    "Data pipelines automate the movement and transformation of information between systems.",
    "Partitioning divides large datasets into smaller sections to improve processing efficiency.",
    "Data orchestration coordinates dependencies and execution across pipeline tasks.",
    "Apache Airflow is commonly used to schedule and orchestrate data workflows.",
    "Data validation checks whether incoming datasets satisfy expected rules.",
    "Data lineage tracks where data originated and how it changed through processing."
]

print("Number of documents:", len(corpus))

Number of documents: 60

In [23]:
assert len(corpus) >= 50, "Corpus must contain at least 50 documents."

print("Corpus validation passed!")
print("Total documents:", len(corpus))

for i, document in enumerate(corpus[:5]):
    print(f"{i}: {document}")

Corpus validation passed!
Total documents: 60
0: Machine learning systems learn patterns from historical data to make predictions.
1: Neural networks are computing models inspired by the structure of biological brains.
2: Natural language processing enables computers to understand and generate human language.
3: Computer vision allows machines to interpret information from images and videos.
4: Large language models can generate text, answer questions, and summarize documents.

In [24]:
import os
from openai import OpenAI

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY is not set.")

client = OpenAI(api_key=api_key)

print("OpenAI client initialized successfully.")

OpenAI client initialized successfully.

In [25]:
import os
from openai import OpenAI

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY is not set.")

client = OpenAI(api_key=api_key)

print("OpenAI client initialized successfully.")

OpenAI client initialized successfully.

In [26]:
def batch_embed(texts, batch_size=20):
    """
    Generate embeddings for a list of texts using OpenAI's
    text-embedding-3-small model.

    Parameters:
        texts: List of strings to embed
        batch_size: Number of texts sent per API request

    Returns:
        NumPy array of float32 embeddings
    """
    
    all_embeddings = []

    for start in range(0, len(texts), batch_size):
        batch = texts[start:start + batch_size]

        response = client.embeddings.create(
            model="text-embedding-3-small",
            input=batch
        )

        batch_embeddings = [
            item.embedding
            for item in response.data
        ]

        all_embeddings.extend(batch_embeddings)

        print(
            f"Embedded {min(start + batch_size, len(texts))}"
            f"/{len(texts)} documents"
        )

    return np.array(all_embeddings, dtype=np.float32)

In [31]:
print("Corpus documents:", len(corpus))

Corpus documents: 60

In [32]:
import os
import numpy as np
from openai import OpenAI

In [33]:
api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError("OPENAI_API_KEY is not set.")

client = OpenAI(api_key=api_key)

print("OpenAI client initialized.")

OpenAI client initialized.

In [34]:
def batch_embed(texts, batch_size=20):
    all_embeddings = []

    for start in range(0, len(texts), batch_size):
        batch = texts[start:start + batch_size]

        response = client.embeddings.create(
            model="text-embedding-3-small",
            input=batch
        )

        batch_embeddings = [item.embedding for item in response.data]

        all_embeddings.extend(batch_embeddings)

        print(
            f"Embedded {min(start + batch_size, len(texts))}"
            f"/{len(texts)} documents"
        )

    return np.array(all_embeddings, dtype=np.float32)

In [37]:
import os

key = os.getenv("OPENAI_API_KEY")

print("Key exists:", bool(key))
print("Key length:", len(key) if key else 0)
print("Key prefix:", key[:7] + "..." if key else "Not set")

Key exists: True
Key length: 24
Key prefix: sk-proj...

In [39]:
import os

key = os.getenv("OPENAI_API_KEY")

print("Key loaded:", bool(key))
print("Key prefix:", key[:7] + "..." if key else "Not set")

Key loaded: True
Key prefix: sk-proj...

In [40]:
from openai import OpenAI
import os

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

print("OpenAI client initialized successfully.")

OpenAI client initialized successfully.

In [42]:
from openai import OpenAI
import os

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

print("Client initialized.")

Client initialized.

In [45]:
import os

key = os.getenv("OPENAI_API_KEY")

print("Key loaded:", bool(key))
print("Key prefix:", key[:7] + "..." if key else "Not set")

Key loaded: True
Key prefix: sk-proj...

In [47]:
from getpass import getpass
from openai import OpenAI

api_key = getpass("Enter your OpenAI API key: ")

client = OpenAI(api_key=api_key)

print("Client created successfully.")

Client created successfully.

In [ ]:
embeddings = batch_embed(corpus)

print("Embedding shape:", embeddings.shape)
print("Embedding dtype:", embeddings.dtype)

In [50]:
import numpy as np
import faiss

dimension = 1536

np.random.seed(42)

embeddings_demo = np.random.random(
    (len(corpus), dimension)
).astype(np.float32)

print("Demo embedding shape:", embeddings_demo.shape)
print("Demo embedding dtype:", embeddings_demo.dtype)

Demo embedding shape: (60, 1536)
Demo embedding dtype: float32

In [51]:
index = faiss.IndexFlatL2(dimension)

print("FAISS index created.")
print("Before adding:", index.ntotal)

index.add(embeddings_demo)

print("After adding:", index.ntotal)
print("Expected:", len(corpus))

assert index.ntotal == len(corpus)

print("FAISS index validation passed!")

FAISS index created.
Before adding: 0
After adding: 60
Expected: 60
FAISS index validation passed!

In [52]:
def embed_query(query):
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=[query]
    )

    return np.array(
        response.data[0].embedding,
        dtype=np.float32
    )


def semantic_search(query, top_k=5):
    query_vector = embed_query(query)

    distances, indices = index.search(
        query_vector.reshape(1, -1),
        top_k
    )

    results = []

    for distance, idx in zip(distances[0], indices[0]):
        results.append({
            "document_index": int(idx),
            "document": corpus[idx],
            "distance": float(distance)
        })

    return results

In [53]:
import re


def keyword_search(query, corpus, top_k=5):
    query_words = set(
        re.findall(r"\b\w+\b", query.lower())
    )

    scored_documents = []

    for idx, document in enumerate(corpus):
        document_words = set(
            re.findall(r"\b\w+\b", document.lower())
        )

        overlap = query_words.intersection(document_words)

        score = len(overlap)

        scored_documents.append({
            "document_index": idx,
            "document": document,
            "score": score,
            "matched_words": sorted(overlap)
        })

    scored_documents.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return scored_documents[:top_k]

In [54]:
query = "How can computers understand human language?"

results = keyword_search(
    query,
    corpus,
    top_k=5
)

for result in results:
    print("Score:", result["score"])
    print("Matched words:", result["matched_words"])
    print("Document:", result["document"])
    print("-" * 80)

Score: 4
Matched words: ['computers', 'human', 'language', 'understand']
Document: Natural language processing enables computers to understand and generate human language.
--------------------------------------------------------------------------------
Score: 2
Matched words: ['can', 'language']
Document: Large language models can generate text, answer questions, and summarize documents.
--------------------------------------------------------------------------------
Score: 2
Matched words: ['can', 'language']
Document: Tokenization breaks text into smaller units that language models can process.
--------------------------------------------------------------------------------
Score: 1
Matched words: ['language']
Document: Retrieval augmented generation combines language models with external knowledge sources.
--------------------------------------------------------------------------------
Score: 1
Matched words: ['language']
Document: Prompt engineering involves designing instructions that guide language model behavior.
--------------------------------------------------------------------------------

In [55]:
test_queries = [
    "How do computers understand what people say?",
    "How can I protect my account from unauthorized access?",
    "What technology helps run containers across many machines?",
    "How can I make frequently requested data load faster?",
    "How do I store huge amounts of raw data?",
    "What checks make sure software changes do not break existing code?",
    "How can applications exchange messages without waiting for each other?",
    "How can a system automatically increase resources when traffic grows?",
    "How do I find weaknesses in my software and infrastructure?",
    "What technology processes data continuously as events arrive?"
]

print("Number of test queries:", len(test_queries))

Number of test queries: 10


## Real OpenAI Embeddings — Requires API Credits

The OpenAI `text-embedding-3-small` API call is currently blocked because
the API project has no remaining credits.

The final implementation below is designed to replace the demo embeddings
once API credits are available.

In [57]:
import re
import pandas as pd


def keyword_search(query, corpus, top_k=5):
    query_words = set(
        re.findall(r"\b\w+\b", query.lower())
    )

    scored_documents = []

    for idx, document in enumerate(corpus):
        document_words = set(
            re.findall(r"\b\w+\b", document.lower())
        )

        overlap = query_words.intersection(document_words)

        scored_documents.append({
            "document_index": idx,
            "document": document,
            "score": len(overlap),
            "matched_words": sorted(overlap)
        })

    scored_documents.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return scored_documents[:top_k]

In [58]:
keyword_summary = []

for query in test_queries:
    result = keyword_search(
        query,
        corpus,
        top_k=1
    )[0]

    keyword_summary.append({
        "Query": query,
        "Keyword Score": result["score"],
        "Keyword Result": result["document"],
        "Matched Words": ", ".join(result["matched_words"])
    })

keyword_df = pd.DataFrame(keyword_summary)

pd.set_option("display.max_colwidth", 120)

keyword_df

,Query,Keyword Score,Keyword Result,Matched Words
0,How do computers understand what people say?,2,Natural language processing enables computers to understand and generate human language.,"computers, understand"
1,How can I protect my account from unauthorized access?,3,"Cybersecurity protects systems, networks, and information from unauthorized access.","access, from, unauthorized"
2,What technology helps run containers across many machines?,3,Kubernetes orchestrates containers across clusters of machines.,"across, containers, machines"
3,How can I make frequently requested data load faster?,3,Caching stores frequently accessed information so future requests can be served faster.,"can, faster, frequently"
4,How do I store huge amounts of raw data?,4,Data lakes store large volumes of raw structured and unstructured information.,"data, of, raw, store"
5,What checks make sure software changes do not break existing code?,2,Git tracks changes to source code and enables collaboration between developers.,"changes, code"
6,How can applications exchange messages without waiting for each other?,2,Containers package applications with their dependencies so they can run consistently.,"applications, can"
7,How can a system automatically increase resources when traffic grows?,2,"ETL pipelines extract data, transform it, and load it into a target system.","a, system"
8,How do I find weaknesses in my software and infrastructure?,4,Vulnerability scanning identifies weaknesses in applications and infrastructure.,"and, in, infrastructure, weaknesses"
9,What technology processes data continuously as events arrive?,3,Stream processing analyzes events continuously as they are generated.,"as, continuously, events"

In [59]:
def faiss_demo_search(query_index, top_k=5):
    """
    Demonstration of FAISS nearest-neighbour retrieval
    using temporary vectors.
    """

    query_vector = embeddings_demo[
        query_index
    ].reshape(1, -1).astype(np.float32)

    distances, indices = index.search(
        query_vector,
        top_k
    )

    results = []

    for distance, idx in zip(
        distances[0],
        indices[0]
    ):
        results.append({
            "document_index": int(idx),
            "document": corpus[idx],
            "distance": float(distance)
        })

    return results

In [60]:
demo_results = faiss_demo_search(
    query_index=0,
    top_k=3
)

for result in demo_results:
    print("Distance:", result["distance"])
    print("Document:", result["document"])
    print("-" * 80)

Distance: 0.0
Document: Machine learning systems learn patterns from historical data to make predictions.
--------------------------------------------------------------------------------
Distance: 244.44287109375
Document: Authorization determines which resources an authenticated user is allowed to access.
--------------------------------------------------------------------------------
Distance: 248.33848571777344
Document: Cloud load balancers distribute incoming traffic across multiple application instances.
--------------------------------------------------------------------------------

In [61]:
def create_real_faiss_index(corpus):
    """
    Generate real OpenAI embeddings and build the final FAISS index.
    """

    embeddings = batch_embed(corpus)

    assert embeddings.dtype == np.float32
    assert embeddings.shape[0] == len(corpus)

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    assert index.ntotal == len(corpus)

    return embeddings, index

In [66]:
import numpy as np
import faiss

dimension = 1536

np.random.seed(42)

embeddings_demo = np.random.random(
    (len(corpus), dimension)
).astype(np.float32)

index = faiss.IndexFlatL2(dimension)
index.add(embeddings_demo)

print("Embedding shape:", embeddings_demo.shape)
print("Embedding dtype:", embeddings_demo.dtype)
print("FAISS index size:", index.ntotal)

assert embeddings_demo.shape == (len(corpus), 1536)
assert embeddings_demo.dtype == np.float32
assert index.ntotal == len(corpus)

print("FAISS validation passed!")

Embedding shape: (60, 1536)
Embedding dtype: float32
FAISS index size: 60
FAISS validation passed!

In [67]:
import re

stop_words = {
    "how", "can", "i", "do", "what", "is", "the",
    "a", "an", "to", "of", "in", "for", "and",
    "my", "from", "on", "with", "that", "this"
}

def keyword_search(query, corpus, top_k=5):
    query_words = set(re.findall(r"\b\w+\b", query.lower()))
    query_words = query_words - stop_words

    scored_documents = []

    for idx, document in enumerate(corpus):
        document_words = set(
            re.findall(r"\b\w+\b", document.lower())
        )

        overlap = query_words.intersection(document_words)

        scored_documents.append({
            "document_index": idx,
            "document": document,
            "score": len(overlap),
            "matched_words": sorted(overlap)
        })

    scored_documents.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return scored_documents[:top_k]

In [68]:
test_queries = [
    "How do computers understand what people say?",
    "How can I protect my account from unauthorized access?",
    "What technology helps run containers across many machines?",
    "How can I make frequently requested data load faster?",
    "How do I store huge amounts of raw data?",
    "What checks make sure software changes do not break existing code?",
    "How can applications exchange messages without waiting for each other?",
    "How can a system automatically increase resources when traffic grows?",
    "How do I find weaknesses in my software and infrastructure?",
    "What technology processes data continuously as events arrive?"
]

print("Number of test queries:", len(test_queries))

Number of test queries: 10

In [69]:
keyword_results = []

for query in test_queries:
    results = keyword_search(
        query,
        corpus,
        top_k=3
    )

    keyword_results.append({
        "Query": query,
        "Top 1 Result": results[0]["document"],
        "Top 1 Score": results[0]["score"],
        "Top 2 Result": results[1]["document"],
        "Top 2 Score": results[1]["score"],
        "Top 3 Result": results[2]["document"],
        "Top 3 Score": results[2]["score"]
    })

keyword_df = pd.DataFrame(keyword_results)

pd.set_option("display.max_colwidth", 120)

keyword_df

,Query,Top 1 Result,Top 1 Score,Top 2 Result,Top 2 Score,Top 3 Result,Top 3 Score
0,How do computers understand what people say?,Natural language processing enables computers to understand and generate human language.,2,Machine learning systems learn patterns from historical data to make predictions.,0,Neural networks are computing models inspired by the structure of biological brains.,0
1,How can I protect my account from unauthorized access?,"Cybersecurity protects systems, networks, and information from unauthorized access.",2,Authorization determines which resources an authenticated user is allowed to access.,1,Machine learning systems learn patterns from historical data to make predictions.,0
2,What technology helps run containers across many machines?,Kubernetes orchestrates containers across clusters of machines.,3,Virtual machines allow multiple isolated computing environments to run on shared hardware.,2,Containers package applications with their dependencies so they can run consistently.,2
3,How can I make frequently requested data load faster?,Machine learning systems learn patterns from historical data to make predictions.,2,"ETL pipelines extract data, transform it, and load it into a target system.",2,Caching stores frequently accessed information so future requests can be served faster.,2
4,How do I store huge amounts of raw data?,Data lakes store large volumes of raw structured and unstructured information.,3,Object storage is designed for storing large amounts of unstructured data.,2,Machine learning systems learn patterns from historical data to make predictions.,1
5,What checks make sure software changes do not break existing code?,Git tracks changes to source code and enables collaboration between developers.,2,Continuous integration automatically builds and tests software changes.,2,Code reviews help teams identify defects and improve software quality.,2
6,How can applications exchange messages without waiting for each other?,Containers package applications with their dependencies so they can run consistently.,1,Serverless computing allows developers to run code without managing servers directly.,1,Microservices divide applications into smaller independently deployable services.,1
7,How can a system automatically increase resources when traffic grows?,Cloud computing provides computing resources over the internet on demand.,1,Auto scaling increases or decreases computing resources based on workload demand.,1,Cloud load balancers distribute incoming traffic across multiple application instances.,1
8,How do I find weaknesses in my software and infrastructure?,Vulnerability scanning identifies weaknesses in applications and infrastructure.,2,Infrastructure as code manages infrastructure through version-controlled configuration files.,1,Continuous integration automatically builds and tests software changes.,1
9,What technology processes data continuously as events arrive?,Stream processing analyzes events continuously as they are generated.,3,Data quality processes help ensure that analytical datasets are accurate and consistent.,2,Machine learning systems learn patterns from historical data to make predictions.,1

In [70]:
keyword_results = []

for query in test_queries:
    results = keyword_search(
        query,
        corpus,
        top_k=3
    )

    keyword_results.append({
        "Query": query,
        "Top 1 Result": results[0]["document"],
        "Top 1 Score": results[0]["score"],
        "Top 2 Result": results[1]["document"],
        "Top 2 Score": results[1]["score"],
        "Top 3 Result": results[2]["document"],
        "Top 3 Score": results[2]["score"]
    })

keyword_df = pd.DataFrame(keyword_results)

pd.set_option("display.max_colwidth", 120)

keyword_df

,Query,Top 1 Result,Top 1 Score,Top 2 Result,Top 2 Score,Top 3 Result,Top 3 Score
0,How do computers understand what people say?,Natural language processing enables computers to understand and generate human language.,2,Machine learning systems learn patterns from historical data to make predictions.,0,Neural networks are computing models inspired by the structure of biological brains.,0
1,How can I protect my account from unauthorized access?,"Cybersecurity protects systems, networks, and information from unauthorized access.",2,Authorization determines which resources an authenticated user is allowed to access.,1,Machine learning systems learn patterns from historical data to make predictions.,0
2,What technology helps run containers across many machines?,Kubernetes orchestrates containers across clusters of machines.,3,Virtual machines allow multiple isolated computing environments to run on shared hardware.,2,Containers package applications with their dependencies so they can run consistently.,2
3,How can I make frequently requested data load faster?,Machine learning systems learn patterns from historical data to make predictions.,2,"ETL pipelines extract data, transform it, and load it into a target system.",2,Caching stores frequently accessed information so future requests can be served faster.,2
4,How do I store huge amounts of raw data?,Data lakes store large volumes of raw structured and unstructured information.,3,Object storage is designed for storing large amounts of unstructured data.,2,Machine learning systems learn patterns from historical data to make predictions.,1
5,What checks make sure software changes do not break existing code?,Git tracks changes to source code and enables collaboration between developers.,2,Continuous integration automatically builds and tests software changes.,2,Code reviews help teams identify defects and improve software quality.,2
6,How can applications exchange messages without waiting for each other?,Containers package applications with their dependencies so they can run consistently.,1,Serverless computing allows developers to run code without managing servers directly.,1,Microservices divide applications into smaller independently deployable services.,1
7,How can a system automatically increase resources when traffic grows?,Cloud computing provides computing resources over the internet on demand.,1,Auto scaling increases or decreases computing resources based on workload demand.,1,Cloud load balancers distribute incoming traffic across multiple application instances.,1
8,How do I find weaknesses in my software and infrastructure?,Vulnerability scanning identifies weaknesses in applications and infrastructure.,2,Infrastructure as code manages infrastructure through version-controlled configuration files.,1,Continuous integration automatically builds and tests software changes.,1
9,What technology processes data continuously as events arrive?,Stream processing analyzes events continuously as they are generated.,3,Data quality processes help ensure that analytical datasets are accurate and consistent.,2,Machine learning systems learn patterns from historical data to make predictions.,1

In [71]:
# Semantic vs Keyword Search Comparison

comparison_notes = {
    "Semantic Search": {
        "status": "Implemented, but live execution requires OpenAI API credits",
        "model": "text-embedding-3-small",
        "index": "FAISS IndexFlatL2",
        "vector_dtype": "float32"
    },
    "Keyword Search": {
        "status": "Implemented and executable locally",
        "method": "Word overlap scoring"
    }
}

comparison_notes

{'Semantic Search': {'status': 'Implemented, but live execution requires OpenAI API credits',
  'model': 'text-embedding-3-small',
  'index': 'FAISS IndexFlatL2',
  'vector_dtype': 'float32'},
 'Keyword Search': {'status': 'Implemented and executable locally',
  'method': 'Word overlap scoring'}}

In [73]:
semantic_wins = [
    {
        "Query": "How do computers understand what people say?",
        "Expected Semantic Result": "Natural language processing enables computers to understand and generate human language.",
        "Reason": "Semantic search can connect 'understand what people say' with natural language processing."
    },
    {
        "Query": "How can I make frequently requested data load faster?",
        "Expected Semantic Result": "Caching stores frequently accessed information so future requests can be served faster.",
        "Reason": "The query describes caching without explicitly using the word 'caching'."
    },
    {
        "Query": "How can a system automatically increase resources when traffic grows?",
        "Expected Semantic Result": "Auto scaling increases or decreases computing resources based on workload demand.",
        "Reason": "Semantic search can connect increasing resources with auto scaling."
    }
]

semantic_wins_df = pd.DataFrame(semantic_wins)

semantic_wins_df

,Query,Expected Semantic Result,Reason
0,How do computers understand what people say?,Natural language processing enables computers to understand and generate human language.,Semantic search can connect 'understand what people say' with natural language processing.
1,How can I make frequently requested data load faster?,Caching stores frequently accessed information so future requests can be served faster.,The query describes caching without explicitly using the word 'caching'.
2,How can a system automatically increase resources when traffic grows?,Auto scaling increases or decreases computing resources based on workload demand.,Semantic search can connect increasing resources with auto scaling.

In [74]:
keyword_wins = [
    {
        "Query": "What language is used to query relational databases?",
        "Expected Keyword Result": "SQL is used to query and manipulate data stored in relational databases.",
        "Reason": "The exact technical term 'SQL' makes keyword matching effective."
    },
    {
        "Query": "What tool tracks changes to source code?",
        "Expected Keyword Result": "Git tracks changes to source code and enables collaboration between developers.",
        "Reason": "The exact phrase 'source code' appears in the document."
    },
    {
        "Query": "What technology helps run containers across many machines?",
        "Expected Keyword Result": "Kubernetes orchestrates containers across clusters of machines.",
        "Reason": "The query contains the exact keyword 'containers'."
    }
]

keyword_wins_df = pd.DataFrame(keyword_wins)

keyword_wins_df

,Query,Expected Keyword Result,Reason
0,What language is used to query relational databases?,SQL is used to query and manipulate data stored in relational databases.,The exact technical term 'SQL' makes keyword matching effective.
1,What tool tracks changes to source code?,Git tracks changes to source code and enables collaboration between developers.,The exact phrase 'source code' appears in the document.
2,What technology helps run containers across many machines?,Kubernetes orchestrates containers across clusters of machines.,The query contains the exact keyword 'containers'.

In [75]:
tradeoff_analysis = {
    "Semantic Search": [
        "Understands meaning and different wording",
        "Works well with natural-language questions",
        "Useful for document retrieval and RAG systems",
        "Requires embedding generation",
        "Has embedding API cost and query latency"
    ],
    "Keyword Search": [
        "Simple and inexpensive",
        "Fast for small datasets",
        "Easy to understand and debug",
        "Excellent for exact technical terms",
        "Weak when query and document use different wording"
    ]
}

tradeoff_df = pd.DataFrame(tradeoff_analysis)

tradeoff_df

,Semantic Search,Keyword Search
0,Understands meaning and different wording,Simple and inexpensive
1,Works well with natural-language questions,Fast for small datasets
2,Useful for document retrieval and RAG systems,Easy to understand and debug
3,Requires embedding generation,Excellent for exact technical terms
4,Has embedding API cost and query latency,Weak when query and document use different wording