# Day 4 — Vectors: Teaching Meaning to Machines

## Objective

In this notebook, I will:

1. Install and import sentence-transformers.
2. Generate embeddings for 5 sentences.
3. Compare sentence pairs using cosine similarity.
4. Observe which sentences are most similar in meaning.
5. Reflect on whether the similarity scores match my intuition.

### Pipeline

Sentences → Embeddings → Cosine Similarity → Semantic Comparison

In [7]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [8]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully!

In [6]:
sentences = [
    "I love eating pizza.",
    "Pizza is my favorite food.",
    "I enjoy programming in Python.",
    "The weather is sunny today.",
    "A car is driving on the highway."
]

for i, sentence in enumerate(sentences, start=1):
    print(f"{i}. {sentence}")

1. I love eating pizza.
2. Pizza is my favorite food.
3. I enjoy programming in Python.
4. The weather is sunny today.
5. A car is driving on the highway.

In [9]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [10]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [11]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [12]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [13]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [14]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [15]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [16]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [17]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [18]:
%pip install -U sentence-transformers scikit-learn pandaszz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (6.0.0)
Requirement already satisfied: scikit-learn in C:\Users\ansh\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pandaszz (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pandaszz

In [19]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [20]:
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully!

In [21]:
sentences = [
    "I love eating pizza.",
    "Pizza is my favorite food.",
    "I enjoy programming in Python.",
    "The weather is sunny today.",
    "A car is driving on the highway."
]

for i, sentence in enumerate(sentences, start=1):
    print(f"{i}. {sentence}")

1. I love eating pizza.
2. Pizza is my favorite food.
3. I enjoy programming in Python.
4. The weather is sunny today.
5. A car is driving on the highway.

In [22]:
print("Sentence:")
print(sentences[0])

print("\nEmbedding vector:")
print(embeddings[0])

Sentence:
I love eating pizza.

Embedding vector:

NameError: name 'embeddings' is not defined

In [23]:
embeddings = model.encode(sentences)

print("Number of sentences:", len(embeddings))
print("Embedding shape:", embeddings.shape)

Number of sentences: 5
Embedding shape: (5, 384)

In [24]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully!

In [25]:
embeddings = model.encode(sentences)

print("Number of sentences:", len(embeddings))
print("Embedding shape:", embeddings.shape)

Number of sentences: 5
Embedding shape: (5, 384)

In [26]:
similarity_matrix = cosine_similarity(embeddings)

print("Cosine Similarity Matrix:")
print(similarity_matrix)

Cosine Similarity Matrix:
[[1.         0.85029817 0.2922345  0.07263452 0.03718187]
 [0.85029817 1.0000004  0.2571357  0.09781039 0.05452302]
 [0.2922345  0.2571357  0.9999999  0.01814687 0.03619007]
 [0.07263452 0.09781039 0.01814687 1.0000001  0.08732624]
 [0.03718187 0.05452302 0.03619007 0.08732624 1.        ]]

In [27]:
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=[f"S{i}" for i in range(1, 6)],
    columns=[f"S{i}" for i in range(1, 6)]
)

similarity_df

          S1        S2        S3        S4        S5
S1  1.000000  0.850298  0.292235  0.072635  0.037182
S2  0.850298  1.000000  0.257136  0.097810  0.054523
S3  0.292235  0.257136  1.000000  0.018147  0.036190
S4  0.072635  0.097810  0.018147  1.000000  0.087326
S5  0.037182  0.054523  0.036190  0.087326  1.000000

In [28]:
pair_results = []

for i in range(len(sentences)):
    for j in range(i + 1, len(sentences)):
        score = similarity_matrix[i][j]
        
        pair_results.append({
            "Sentence 1": sentences[i],
            "Sentence 2": sentences[j],
            "Cosine Similarity": round(float(score), 4)
        })

pair_df = pd.DataFrame(pair_results)

pair_df

,Sentence 1,Sentence 2,Cosine Similarity
0,I love eating pizza.,Pizza is my favorite food.,0.8503
1,I love eating pizza.,I enjoy programming in Python.,0.2922
2,I love eating pizza.,The weather is sunny today.,0.0726
3,I love eating pizza.,A car is driving on the highway.,0.0372
4,Pizza is my favorite food.,I enjoy programming in Python.,0.2571
5,Pizza is my favorite food.,The weather is sunny today.,0.0978
6,Pizza is my favorite food.,A car is driving on the highway.,0.0545
7,I enjoy programming in Python.,The weather is sunny today.,0.0181
8,I enjoy programming in Python.,A car is driving on the highway.,0.0362
9,The weather is sunny today.,A car is driving on the highway.,0.0873

In [29]:
highest_pair = pair_df.loc[
    pair_df["Cosine Similarity"].idxmax()
]

print("Most Similar Pair")
print("------------------")
print("Sentence 1:", highest_pair["Sentence 1"])
print("Sentence 2:", highest_pair["Sentence 2"])
print("Similarity Score:", highest_pair["Cosine Similarity"])

Most Similar Pair
------------------
Sentence 1: I love eating pizza.
Sentence 2: Pizza is my favorite food.
Similarity Score: 0.8503

In [30]:
ranked_pairs = pair_df.sort_values(
    by="Cosine Similarity",
    ascending=False
).reset_index(drop=True)

ranked_pairs

,Sentence 1,Sentence 2,Cosine Similarity
0,I love eating pizza.,Pizza is my favorite food.,0.8503
1,I love eating pizza.,I enjoy programming in Python.,0.2922
2,Pizza is my favorite food.,I enjoy programming in Python.,0.2571
3,Pizza is my favorite food.,The weather is sunny today.,0.0978
4,The weather is sunny today.,A car is driving on the highway.,0.0873
5,I love eating pizza.,The weather is sunny today.,0.0726
6,Pizza is my favorite food.,A car is driving on the highway.,0.0545
7,I love eating pizza.,A car is driving on the highway.,0.0372
8,I enjoy programming in Python.,A car is driving on the highway.,0.0362
9,I enjoy programming in Python.,The weather is sunny today.,0.0181

## Reflection

The two pizza-related sentences received the highest similarity score, which matched my intuition because both sentences express a similar meaning.

I was surprised that the embedding model can identify semantic similarity even when sentences do not use exactly the same words. This shows that embeddings capture meaning rather than simply counting words.

Compared with Bag-of-Words, embeddings provide a more useful representation when we want to compare the meaning of sentences.

## Conclusion

In this task, I generated vector embeddings for five sentences using Sentence Transformers.

I used cosine similarity to compare the meaning of different sentence pairs and observed which pairs were most similar.

This demonstrated how text can be represented as numerical vectors and how embeddings can capture semantic relationships between sentences.

Embeddings are an important foundation for applications such as semantic search, recommendation systems, RAG, and clustering.