In [1]:
import wikipedia

# Load a long Wikipedia article
page = wikipedia.page("Natural language processing", auto_suggest=False)

# Store the complete article as a plain string
document = page.content

print("Document title:", page.title)
print("Document characters:", len(document))
print("Approx. words:", len(document.split()))

Document title: Natural language processing
Document characters: 32165
Approx. words: 4495

In [2]:
import wikipedia

page = wikipedia.page("Natural language processing", auto_suggest=False)

document = page.content

print("Document title:", page.title)
print("Document characters:", len(document))
print("Approx. words:", len(document.split()))

Document title: Natural language processing
Document characters: 32165
Approx. words: 4495

In [3]:
import sys
print(sys.executable)

c:\Users\ansh\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [4]:
# Manual fixed-size chunking
def fixed_size_chunking(text, chunk_size):
    chunks = []

    for start in range(0, len(text), chunk_size):
        chunk = text[start:start + chunk_size]
        chunks.append(chunk)

    return chunks

In [5]:
# Create 500-character chunks
fixed_chunks_500 = fixed_size_chunking(document, 500)

print("Total chunks:", len(fixed_chunks_500))

print("\nFirst chunk:")
print(fixed_chunks_500[0])

print("\nSecond chunk:")
print(fixed_chunks_500[1])

Total chunks: 65

First chunk:
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

Natura

Second chunk:
l language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence," which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. The proposed test includes a task that involves the automated interpretation and generation of natural language.


=== Symbolic NLP (1950s – early 1990s) ===

The premise of s

In [6]:
chunk_sizes = [100, 300, 500, 1000]

fixed_chunks = {}

for size in chunk_sizes:
    chunks = fixed_size_chunking(document, size)
    fixed_chunks[size] = chunks

    print(f"Chunk size {size}: {len(chunks)} chunks")

Chunk size 100: 322 chunks
Chunk size 300: 108 chunks
Chunk size 500: 65 chunks
Chunk size 1000: 33 chunks

In [7]:
# Show where the first few chunks end
for i, chunk in enumerate(fixed_chunks[500][:3]):
    print(f"\n--- Chunk {i} ---")
    print("Length:", len(chunk))
    print(chunk[-100:])

--- Chunk 0 ---
Length: 500
sification, natural language understanding, and natural language generation.


== History ==

Natura

--- Chunk 1 ---
Length: 500
n and generation of natural language.


=== Symbolic NLP (1950s – early 1990s) ===

The premise of s

--- Chunk 2 ---
Length: 500
ty Russian sentences into English. The authors claimed that within three or five years, machine tran

In [8]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [9]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

print("LangChain Text Splitter imported successfully!")

LangChain Text Splitter imported successfully!

In [10]:
import sys
print(sys.executable)

c:\Users\ansh\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [11]:
def recursive_chunking(text, chunk_size, chunk_overlap):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""]
    )
    return splitter.split_text(text)

In [12]:
import numpy as np
import pandas as pd

In [13]:
chunk_sizes = [100, 300, 500, 1000]
overlaps = [0, 50, 100]

experiment_results = []

for chunk_size in chunk_sizes:
    for overlap in overlaps:

        if overlap >= chunk_size:
            actual_overlap = chunk_size - 1
        else:
            actual_overlap = overlap

        chunks = recursive_chunking(
            document,
            chunk_size=chunk_size,
            chunk_overlap=actual_overlap
        )

        experiment_results.append({
            "chunk_size": chunk_size,
            "requested_overlap": overlap,
            "actual_overlap": actual_overlap,
            "num_chunks": len(chunks),
            "avg_chunk_length": round(
                np.mean([len(chunk) for chunk in chunks]), 2
            ),
            "min_chunk_length": min(len(chunk) for chunk in chunks),
            "max_chunk_length": max(len(chunk) for chunk in chunks),
            "chunks": chunks
        })

print("Total configurations:", len(experiment_results))

Total configurations: 12

In [14]:
experiment_df = pd.DataFrame(experiment_results)

display(
    experiment_df[
        [
            "chunk_size",
            "requested_overlap",
            "actual_overlap",
            "num_chunks",
            "avg_chunk_length",
            "min_chunk_length",
            "max_chunk_length"
        ]
    ]
)

,chunk_size,requested_overlap,actual_overlap,num_chunks,avg_chunk_length,min_chunk_length,max_chunk_length
0,100,0,0,448,69.46,1,100
1,100,50,50,563,79.63,1,100
2,100,100,99,1553,90.76,1,100
3,300,0,0,180,176.59,10,300
4,300,50,50,181,179.65,10,300
5,300,100,100,185,186.32,10,300
6,500,0,0,101,315.70,26,496
7,500,50,50,101,318.63,26,496
8,500,100,100,102,322.61,26,496
9,1000,0,0,53,603.34,26,996
10,1000,50,50,54,599.59,26,996
11,1000,100,100,54,602.39,26,996

In [15]:
def retrieve_chunks(chunks, query, top_k=3):
    """
    Retrieve the most relevant chunks using TF-IDF cosine similarity.
    """
    
    texts = chunks + [query]

    vectorizer = TfidfVectorizer(stop_words="english")
    tfidf_matrix = vectorizer.fit_transform(texts)

    document_vectors = tfidf_matrix[:-1]
    query_vector = tfidf_matrix[-1]

    similarities = cosine_similarity(
        query_vector,
        document_vectors
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for index in top_indices:
        results.append({
            "chunk_index": int(index),
            "score": float(similarities[index]),
            "text": chunks[index]
        })

    return results

In [16]:
query = "How does natural language processing enable computers to understand and process human language?"

print("Retrieval query:")
print(query)

Retrieval query:
How does natural language processing enable computers to understand and process human language?

In [17]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from langchain_text_splitters import RecursiveCharacterTextSplitter

In [18]:
print("All required imports loaded successfully!")

All required imports loaded successfully!

In [19]:
def retrieve_chunks(chunks, query, top_k=3):
    """
    Retrieve the most relevant chunks using TF-IDF cosine similarity.
    """
    
    texts = chunks + [query]

    vectorizer = TfidfVectorizer(stop_words="english")
    tfidf_matrix = vectorizer.fit_transform(texts)

    document_vectors = tfidf_matrix[:-1]
    query_vector = tfidf_matrix[-1]

    similarities = cosine_similarity(
        query_vector,
        document_vectors
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = []

    for index in top_indices:
        results.append({
            "chunk_index": int(index),
            "score": float(similarities[index]),
            "text": chunks[index]
        })

    return results

In [20]:
test_chunks = recursive_chunking(
    document,
    chunk_size=500,
    chunk_overlap=50
)

query = "How does natural language processing enable computers to understand and process human language?"

results = retrieve_chunks(
    test_chunks,
    query,
    top_k=3
)

for i, result in enumerate(results, 1):
    print(f"\n{'=' * 70}")
    print(f"Result {i}")
    print(f"Chunk index: {result['chunk_index']}")
    print(f"Similarity score: {result['score']:.4f}")
    print("-" * 70)
    print(result["text"])

======================================================================
Result 1
Chunk index: 0
Similarity score: 0.2346
----------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

======================================================================
Result 2
Chunk index: 11
Similarity score: 0.1960
----------------------------------------------------------------------
Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules. Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing. This shift was influenced by increasing computational power (see Moore's law) and a decline in the dominance of Chomskyan linguistic theories (e.g

======================================================================
Result 3
Chunk index: 74
Similarity score: 0.1753
----------------------------------------------------------------------
Natural language generation (NLG):
Convert information from computer databases or semantic intents into readable human language.
Book generation

In [21]:
retrieval_results = []

for result in experiment_results:

    config_name = (
        f"size_{result['chunk_size']}_"
        f"overlap_{result['requested_overlap']}"
    )

    retrieved = retrieve_chunks(
        result["chunks"],
        query,
        top_k=3
    )

    for rank, item in enumerate(retrieved, 1):
        retrieval_results.append({
            "configuration": config_name,
            "chunk_size": result["chunk_size"],
            "overlap": result["requested_overlap"],
            "rank": rank,
            "chunk_index": item["chunk_index"],
            "similarity_score": round(item["score"], 4),
            "retrieved_text": item["text"]
        })

retrieval_df = pd.DataFrame(retrieval_results)

print("Total configurations:", len(experiment_results))
print("Total retrieved chunks:", len(retrieval_df))

Total configurations: 12
Total retrieved chunks: 36

In [22]:
top_results = retrieval_df[
    retrieval_df["rank"] == 1
].sort_values(
    "similarity_score",
    ascending=False
)

display(
    top_results[
        [
            "configuration",
            "chunk_size",
            "overlap",
            "chunk_index",
            "similarity_score"
        ]
    ].reset_index(drop=True)
)

            configuration  chunk_size  overlap  chunk_index  similarity_score
0      size_100_overlap_0         100        0           12            0.4095
1     size_100_overlap_50         100       50            0            0.3929
2    size_100_overlap_100         100      100            0            0.3653
3     size_300_overlap_50         300       50           24            0.2571
4      size_300_overlap_0         300        0           24            0.2565
5    size_300_overlap_100         300      100           24            0.2537
6     size_500_overlap_50         500       50            0            0.2346
7      size_500_overlap_0         500        0            0            0.2345
8    size_500_overlap_100         500      100            0            0.2341
9    size_1000_overlap_50        1000       50            0            0.1958
10  size_1000_overlap_100        1000      100            0            0.1958
11    size_1000_overlap_0        1000        0            0            0.1937

In [23]:
for _, row in top_results.iterrows():

    print("\n" + "=" * 90)
    print(f"Configuration : {row['configuration']}")
    print(f"Similarity    : {row['similarity_score']}")
    print(f"Chunk index   : {row['chunk_index']}")
    print("-" * 90)
    print(row["retrieved_text"])

==========================================================================================
Configuration : size_100_overlap_0
Similarity    : 0.4095
Chunk index   : 12
------------------------------------------------------------------------------------------
natural language.

==========================================================================================
Configuration : size_100_overlap_50
Similarity    : 0.3929
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer

==========================================================================================
Configuration : size_100_overlap_100
Similarity    : 0.3653
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer

==========================================================================================
Configuration : size_300_overlap_50
Similarity    : 0.2571
Chunk index   : 24
------------------------------------------------------------------------------------------
Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules. Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing

==========================================================================================
Configuration : size_300_overlap_0
Similarity    : 0.2565
Chunk index   : 24
------------------------------------------------------------------------------------------
Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules. Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing

==========================================================================================
Configuration : size_300_overlap_100
Similarity    : 0.2537
Chunk index   : 24
------------------------------------------------------------------------------------------
Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules. Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing

==========================================================================================
Configuration : size_500_overlap_50
Similarity    : 0.2346
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

==========================================================================================
Configuration : size_500_overlap_0
Similarity    : 0.2345
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

==========================================================================================
Configuration : size_500_overlap_100
Similarity    : 0.2341
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

==========================================================================================
Configuration : size_1000_overlap_50
Similarity    : 0.1958
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

Natural language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence," which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. The proposed test includes a task that involves the automated interpretation and generation of natural language.


=== Symbolic NLP (1950s – early 1990s) ===

==========================================================================================
Configuration : size_1000_overlap_100
Similarity    : 0.1958
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

Natural language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence," which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. The proposed test includes a task that involves the automated interpretation and generation of natural language.


=== Symbolic NLP (1950s – early 1990s) ===

==========================================================================================
Configuration : size_1000_overlap_0
Similarity    : 0.1937
Chunk index   : 0
------------------------------------------------------------------------------------------
Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.


== History ==

Natural language processing has its roots in the 1950s. Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence," which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. The proposed test includes a task that involves the automated interpretation and generation of natural language.


=== Symbolic NLP (1950s – early 1990s) ===

In [24]:
# Manually assign contextual completeness scores
# based on the retrieved top chunk shown above.

context_scores = {
    # Example format:
    # "size_100_overlap_0": 1,
    # "size_100_overlap_50": 2,
}

print("Add scores for all 12 configurations.")
print("0 = Poor, 1 = Partial, 2 = Complete")

Add scores for all 12 configurations.
0 = Poor, 1 = Partial, 2 = Complete

In [25]:
def find_boundary_failures(text, chunk_size, max_examples=3):
    failures = []

    # Check every fixed-size boundary
    for boundary in range(chunk_size, len(text), chunk_size):

        # Character immediately before and after boundary
        before = text[max(0, boundary - 100):boundary]
        after = text[boundary:boundary + 100]

        # Find sentence punctuation around the boundary
        last_period = before.rfind(".")
        next_period = after.find(".")

        # If there is no sentence-ending period near the boundary,
        # the boundary may have split a sentence.
        if last_period == -1 or next_period == -1:
            
            failures.append({
                "character_position": boundary,
                "before_boundary": before,
                "after_boundary": after
            })

        if len(failures) >= max_examples:
            break

    return failures

In [26]:
def find_boundary_failures(text, chunk_size, max_examples=3):
    failures = []

    for boundary in range(chunk_size, len(text), chunk_size):

        before = text[max(0, boundary - 100):boundary]
        after = text[boundary:boundary + 100]

        last_period = before.rfind(".")
        next_period = after.find(".")

        if last_period == -1 or next_period == -1:
            failures.append({
                "character_position": boundary,
                "before_boundary": before,
                "after_boundary": after
            })

        if len(failures) >= max_examples:
            break

    return failures

In [28]:
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/Artificial_intelligence"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

paragraphs = soup.select("p")

document_text = "\n\n".join(
    p.get_text(" ", strip=True)
    for p in paragraphs
    if len(p.get_text(" ", strip=True)) > 50
)

print("Document loaded successfully!")
print("Total characters:", len(document_text))
print("Total words:", len(document_text.split()))

Document loaded successfully!
Total characters: 88917
Total words: 14700

In [29]:
boundary_failures = find_boundary_failures(
    document_text,
    chunk_size=500,
    max_examples=3
)

print("Total boundary failures found:", len(boundary_failures))

for i, failure in enumerate(boundary_failures, start=1):
    print("\n" + "=" * 80)
    print(f"BOUNDARY FAILURE {i}")
    print("=" * 80)

    print(
        "Exact character position:",
        failure["character_position"]
    )

    print("\nBefore boundary:")
    print(failure["before_boundary"])

    print("\n>>> CHUNK BOUNDARY <<<")

    print("\nAfter boundary:")
    print(failure["after_boundary"])

Total boundary failures found: 3

================================================================================
BOUNDARY FAILURE 1
================================================================================
Exact character position: 500

Before boundary:
d use learning and intelligence to take actions that maximise their chances of achieving defined goa

>>> CHUNK BOUNDARY <<<

After boundary:
ls. [ 1 ]

High-profile applications of AI include advanced web search engines , chatbots , virtual

================================================================================
BOUNDARY FAILURE 2
================================================================================
Exact character position: 1000

Before boundary:
n , as well as support for robotics . [ a ] To reach these goals, AI researchers use techniques incl

>>> CHUNK BOUNDARY <<<

After boundary:
uding state space search and mathematical optimisation , formal logic , artificial neural networks ,

================================================================================
BOUNDARY FAILURE 3
================================================================================
Exact character position: 3000

Before boundary:
thods were developed for dealing with uncertain or incomplete information, employing concepts from p

>>> CHUNK BOUNDARY <<<

After boundary:
robability and economics . [ 13 ]

Many of these algorithms were insufficient for solving large reas

In [30]:
def find_boundary_failures(text, chunk_size, max_examples=3):
    failures = []

    for boundary in range(chunk_size, len(text), chunk_size):

        before = text[max(0, boundary - 100):boundary]
        after = text[boundary:boundary + 100]

        last_period = before.rfind(".")
        next_period = after.find(".")

        if last_period == -1 or next_period == -1:
            failures.append({
                "character_position": boundary,
                "before_boundary": before,
                "after_boundary": after
            })

        if len(failures) >= max_examples:
            break

    return failures

In [31]:
boundary_failures = find_boundary_failures(
    document_text,
    chunk_size=500,
    max_examples=3
)

print("Total boundary failures found:", len(boundary_failures))

for i, failure in enumerate(boundary_failures, start=1):
    print("\n" + "=" * 80)
    print(f"BOUNDARY FAILURE {i}")
    print("=" * 80)

    print(
        "Exact character position:",
        failure["character_position"]
    )

    print("\nBefore boundary:")
    print(failure["before_boundary"])

    print("\n>>> CHUNK BOUNDARY <<<")

    print("\nAfter boundary:")
    print(failure["after_boundary"])

Total boundary failures found: 3

================================================================================
BOUNDARY FAILURE 1
================================================================================
Exact character position: 500

Before boundary:
d use learning and intelligence to take actions that maximise their chances of achieving defined goa

>>> CHUNK BOUNDARY <<<

After boundary:
ls. [ 1 ]

High-profile applications of AI include advanced web search engines , chatbots , virtual

================================================================================
BOUNDARY FAILURE 2
================================================================================
Exact character position: 1000

Before boundary:
n , as well as support for robotics . [ a ] To reach these goals, AI researchers use techniques incl

>>> CHUNK BOUNDARY <<<

After boundary:
uding state space search and mathematical optimisation , formal logic , artificial neural networks ,

================================================================================
BOUNDARY FAILURE 3
================================================================================
Exact character position: 3000

Before boundary:
thods were developed for dealing with uncertain or incomplete information, employing concepts from p

>>> CHUNK BOUNDARY <<<

After boundary:
robability and economics . [ 13 ]

Many of these algorithms were insufficient for solving large reas

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def retrieve_best_chunk(chunks, query):
    corpus = chunks + [query]

    vectorizer = TfidfVectorizer(
        stop_words="english"
    )

    vectors = vectorizer.fit_transform(corpus)

    chunk_vectors = vectors[:-1]
    query_vector = vectors[-1]

    similarities = cosine_similarity(
        query_vector,
        chunk_vectors
    ).flatten()

    best_index = similarities.argmax()

    return {
        "chunk_index": int(best_index),
        "score": float(similarities[best_index]),
        "chunk": chunks[best_index]
    }

In [34]:
retrieval_query = (
    "What are the goals, capabilities and applications "
    "of artificial intelligence?"
)

print("Retrieval query:")
print(retrieval_query)

Retrieval query:
What are the goals, capabilities and applications of artificial intelligence?

In [35]:
chunk_sizes = [100, 300, 500, 1000]
overlaps = [0, 50, 100]

experiment_results = []

for chunk_size in chunk_sizes:
    for overlap in overlaps:

        try:
            chunks = recursive_chunking(
                document_text,
                chunk_size=chunk_size,
                chunk_overlap=overlap
            )

            result = retrieve_best_chunk(
                chunks,
                retrieval_query
            )

            experiment_results.append({
                "chunk_size": chunk_size,
                "overlap": overlap,
                "num_chunks": len(chunks),
                "retrieval_score": result["score"],
                "retrieved_chunk": result["chunk"],
                "status": "success"
            })

        except Exception as e:
            experiment_results.append({
                "chunk_size": chunk_size,
                "overlap": overlap,
                "num_chunks": None,
                "retrieval_score": None,
                "retrieved_chunk": str(e),
                "status": "error"
            })

results_df = pd.DataFrame(experiment_results)

print("Total configurations:", len(results_df))

results_df[
    [
        "chunk_size",
        "overlap",
        "num_chunks",
        "retrieval_score",
        "status"
    ]
]

Total configurations: 12

    chunk_size  overlap  num_chunks  retrieval_score   status
0          100        0        1288         0.463318  success
1          100       50        1593         0.378761  success
2          100      100        4658         0.381046  success
3          300        0         446         0.256817  success
4          300       50         447         0.256911  success
5          300      100         459         0.253322  success
6          500        0         265         0.216498  success
7          500       50         265         0.216498  success
8          500      100         267         0.215834  success
9         1000        0         127         0.208787  success
10        1000       50         127         0.208787  success
11        1000      100         127         0.208787  success

In [36]:
important_terms = [
    "intelligence",
    "goal",
    "capabilities",
    "applications",
    "learning",
    "reasoning",
    "problem",
    "knowledge"
]

def contextual_completeness(chunk):
    text = chunk.lower()

    matched_terms = [
        term
        for term in important_terms
        if term in text
    ]

    score = len(matched_terms) / len(important_terms)

    return score, matched_terms

In [37]:
results_df["context_completeness"] = 0.0
results_df["quality_score"] = 0.0

for index, row in results_df.iterrows():

    if row["status"] != "success":
        continue

    completeness, matched_terms = contextual_completeness(
        row["retrieved_chunk"]
    )

    results_df.loc[index, "context_completeness"] = completeness

    results_df.loc[index, "quality_score"] = (
        row["retrieval_score"] * 0.6
        + completeness * 0.4
    )

results_df[
    [
        "chunk_size",
        "overlap",
        "num_chunks",
        "retrieval_score",
        "context_completeness",
        "quality_score",
        "status"
    ]
]

,chunk_size,overlap,num_chunks,retrieval_score,context_completeness,quality_score,status
0,100,0,1288,0.463318,0.125,0.327991,success
1,100,50,1593,0.378761,0.250,0.327257,success
2,100,100,4658,0.381046,0.250,0.328627,success
3,300,0,446,0.256817,0.375,0.304090,success
4,300,50,447,0.256911,0.375,0.304147,success
5,300,100,459,0.253322,0.375,0.301993,success
6,500,0,265,0.216498,0.375,0.279899,success
7,500,50,265,0.216498,0.375,0.279899,success
8,500,100,267,0.215834,0.375,0.279500,success
9,1000,0,127,0.208787,0.375,0.275272,success
10,1000,50,127,0.208787,0.375,0.275272,success
11,1000,100,127,0.208787,0.375,0.275272,success

In [38]:
successful_results = results_df[
    results_df["status"] == "success"
].copy()

successful_results = successful_results.sort_values(
    by="quality_score",
    ascending=False
).reset_index(drop=True)

best_result = successful_results.iloc[0]

print("=" * 70)
print("BEST CHUNKING CONFIGURATION")
print("=" * 70)

print("Chunk Size:", int(best_result["chunk_size"]))
print("Overlap:", int(best_result["overlap"]))
print("Number of Chunks:", int(best_result["num_chunks"]))
print("Retrieval Score:", round(best_result["retrieval_score"], 4))
print("Context Completeness:", round(best_result["context_completeness"], 4))
print("Overall Quality Score:", round(best_result["quality_score"], 4))

print("\nRetrieved Context:")
print("-" * 70)
print(best_result["retrieved_chunk"])

======================================================================
BEST CHUNKING CONFIGURATION
======================================================================
Chunk Size: 100
Overlap: 100
Number of Chunks: 4658
Retrieval Score: 0.381
Context Completeness: 0.25
Overall Quality Score: 0.3286

Retrieved Context:
----------------------------------------------------------------------
the goals of artificial general intelligence and superintelligence directly or to solve as many

In [39]:
successful_results[
    [
        "chunk_size",
        "overlap",
        "num_chunks",
        "retrieval_score",
        "context_completeness",
        "quality_score"
    ]
]

,chunk_size,overlap,num_chunks,retrieval_score,context_completeness,quality_score
0,100,100,4658,0.381046,0.250,0.328627
1,100,0,1288,0.463318,0.125,0.327991
2,100,50,1593,0.378761,0.250,0.327257
3,300,50,447,0.256911,0.375,0.304147
4,300,0,446,0.256817,0.375,0.304090
5,300,100,459,0.253322,0.375,0.301993
6,500,0,265,0.216498,0.375,0.279899
7,500,50,265,0.216498,0.375,0.279899
8,500,100,267,0.215834,0.375,0.279500
9,1000,0,127,0.208787,0.375,0.275272
10,1000,50,127,0.208787,0.375,0.275272
11,1000,100,127,0.208787,0.375,0.275272

In [40]:
top_configs = successful_results[
    [
        "chunk_size",
        "overlap",
        "num_chunks",
        "retrieval_score",
        "context_completeness",
        "quality_score"
    ]
].head(5)

top_configs

,chunk_size,overlap,num_chunks,retrieval_score,context_completeness,quality_score
0,100,100,4658,0.381046,0.250,0.328627
1,100,0,1288,0.463318,0.125,0.327991
2,100,50,1593,0.378761,0.250,0.327257
3,300,50,447,0.256911,0.375,0.304147
4,300,0,446,0.256817,0.375,0.304090

In [41]:
print("FINAL RECOMMENDATION")
print("=" * 70)

print(
    f"Chunk Size : {int(best_result['chunk_size'])} characters"
)

print(
    f"Overlap    : {int(best_result['overlap'])} characters"
)

print(
    f"Retrieval Score : "
    f"{best_result['retrieval_score']:.4f}"
)

print(
    f"Context Completeness : "
    f"{best_result['context_completeness']:.4f}"
)

print(
    f"Overall Quality Score : "
    f"{best_result['quality_score']:.4f}"
)

FINAL RECOMMENDATION
======================================================================
Chunk Size : 100 characters
Overlap    : 100 characters
Retrieval Score : 0.3810
Context Completeness : 0.2500
Overall Quality Score : 0.3286

In [42]:
boundary_examples = []

for i, failure in enumerate(boundary_failures[:3], start=1):
    boundary_examples.append({
        "Example": i,
        "Character Position": failure["character_position"],
        "Before Boundary": failure["before_boundary"],
        "After Boundary": failure["after_boundary"]
    })

boundary_df = pd.DataFrame(boundary_examples)

boundary_df

,Example,Character Position,Before Boundary,After Boundary
0,1,500,d use learning and intelligence to take action...,ls. [ 1 ]\n\nHigh-profile applications of AI i...
1,2,1000,"n , as well as support for robotics . [ a ] To...",uding state space search and mathematical opti...
2,3,3000,thods were developed for dealing with uncertai...,robability and economics . [ 13 ]\n\nMany of t...

In [43]:
for i, failure in enumerate(boundary_failures[:3], start=1):

    print("\n" + "=" * 90)
    print(f"BOUNDARY FAILURE EXAMPLE {i}")
    print("=" * 90)

    print(
        f"Exact character position: "
        f"{failure['character_position']}"
    )

    print("\n--- End of previous chunk ---")
    print(failure["before_boundary"])

    print("\n******** CHUNK BOUNDARY ********")

    print("\n--- Start of next chunk ---")
    print(failure["after_boundary"])

==========================================================================================
BOUNDARY FAILURE EXAMPLE 1
==========================================================================================
Exact character position: 500

--- End of previous chunk ---
d use learning and intelligence to take actions that maximise their chances of achieving defined goa

******** CHUNK BOUNDARY ********

--- Start of next chunk ---
ls. [ 1 ]

High-profile applications of AI include advanced web search engines , chatbots , virtual

==========================================================================================
BOUNDARY FAILURE EXAMPLE 2
==========================================================================================
Exact character position: 1000

--- End of previous chunk ---
n , as well as support for robotics . [ a ] To reach these goals, AI researchers use techniques incl

******** CHUNK BOUNDARY ********

--- Start of next chunk ---
uding state space search and mathematical optimisation , formal logic , artificial neural networks ,

==========================================================================================
BOUNDARY FAILURE EXAMPLE 3
==========================================================================================
Exact character position: 3000

--- End of previous chunk ---
thods were developed for dealing with uncertain or incomplete information, employing concepts from p

******** CHUNK BOUNDARY ********

--- Start of next chunk ---
robability and economics . [ 13 ]

Many of these algorithms were insufficient for solving large reas

# Final Chunking Strategy Recommendation

## Experimental Findings

This experiment compared manual fixed-size chunking with LangChain's
RecursiveCharacterTextSplitter on a long Wikipedia article about Artificial
Intelligence.

Four chunk sizes were evaluated:

- 100 characters
- 300 characters
- 500 characters
- 1000 characters

Three overlap values were evaluated:

- 0 characters
- 50 characters
- 100 characters

This resulted in 12 chunking configurations.

The same retrieval query was used for every configuration:

> What are the goals, capabilities and applications of artificial intelligence?

## Results

The experiment showed that very small chunks provide highly focused text but
can lose important surrounding context. Larger chunks preserve more context,
but they may also introduce irrelevant information into the retrieved result.

Chunk overlap helps preserve continuity when an important sentence or concept
falls close to a chunk boundary.

The best-performing configuration was selected using a combined quality score
based on retrieval similarity and contextual completeness.

## Recommended Strategy

For this document, the recommended configuration is the configuration with
the highest overall quality score reported by the experiment.

The general recommendation for similar long-form documents is to start with:

- Chunk size: 500 characters
- Chunk overlap: 50-100 characters
- Strategy: RecursiveCharacterTextSplitter

This provides a useful balance between context preservation and retrieval
precision.

## Boundary Failure Analysis

Manual fixed-size chunking demonstrated that arbitrary character boundaries
can split sentences in the middle of a thought.

Three such boundary failures were identified and documented with their exact
character positions in the experiment.

These failures demonstrate why semantic-aware recursive splitting is generally
preferable to naive fixed-size splitting for Retrieval-Augmented Generation
(RAG) systems.

## Conclusion

Chunking is not simply a preprocessing step. It directly affects retrieval
quality.

The experiment demonstrates that:

1. Very small chunks can lose context.
2. Very large chunks can contain unnecessary information.
3. Overlap helps maintain continuity.
4. Recursive splitting produces more natural boundaries.
5. Chunk size should be selected based on document structure and retrieval
   requirements.

In [44]:
print("DAY 12 CHUNKING EXPERIMENT COMPLETE")
print("=" * 70)
print("Document characters:", len(document_text))
print("Configurations tested:", len(results_df))
print("Boundary examples documented:", len(boundary_failures[:3]))

print(
    "Best chunk size:",
    int(best_result["chunk_size"])
)

print(
    "Best overlap:",
    int(best_result["overlap"])
)

print(
    "Best quality score:",
    round(best_result["quality_score"], 4)
)

DAY 12 CHUNKING EXPERIMENT COMPLETE
======================================================================
Document characters: 88917
Configurations tested: 12
Boundary examples documented: 3
Best chunk size: 100
Best overlap: 100
Best quality score: 0.3286